# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3ca9666c5bf16887feac238cac9d94b7"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Measure Pro"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
